# Generated by Django 4.2.4 on 2023-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(max_length=1000),
        ),
    ]
