# Generated by Django 4.2.4 on 2023-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default='media/abc.jpg', upload_to='media/'),
        ),
    ]
