# Generated by Django 4.2.4 on 2023-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0005_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_firstname', models.CharField(max_length=50)),
                ('Seller_email', models.EmailField(max_length=50, unique=True)),
                ('Seller_password', models.CharField(max_length=1000)),
                ('Seller_image', models.FileField(default='/abc.jpg', upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='/abc.jpg', upload_to='media/'),
        ),
    ]
