# Generated by Django 4.2.4 on 2023-08-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0007_rename_seller_firstname_seller_user_seller_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing_immage', models.FileField(default='Listing/abc.jpg', upload_to='Listing/')),
                ('P_name', models.CharField(max_length=100)),
                ('P_Price', models.IntegerField(default=0)),
                ('P_sellprice', models.CharField(max_length=100)),
                ('P_Quntity', models.IntegerField(default=0)),
                ('P_Color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=100)),
                ('P_Description', models.CharField(max_length=500)),
                ('P_Categary', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
