# Generated by Django 4.2.4 on 2023-08-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0008_listing_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing_data',
            new_name='Listing_Product',
        ),
    ]
