# Generated by Django 4.2.4 on 2023-08-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0010_listing_product_seller_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing_product',
            old_name='Seller_id',
            new_name='seller_id',
        ),
    ]
