# Generated by Django 4.2.4 on 2023-08-29 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0011_rename_seller_id_listing_product_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quntity', models.IntegerField(default=0)),
                ('product_color', models.CharField(max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('Bayer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bayur.user')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bayur.listing_product')),
            ],
        ),
    ]
