# Generated by Django 4.2.4 on 2023-08-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0012_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='Total',
        ),
    ]
